Rails.application.routes.draw do
  # generated by: rails generate controller Articles index new
  get 'articles', to: 'articles#index'
  # get 'articles/index'
  get 'articles/new'

  # Defines the root path route ("/")
  # root "articles#index"
  # get '', to: 'articles#index' # same as above

  # get 'articles', to: 'articles#index'
  # get 'articles/:id', to: 'articles#show'

  # contains all articles paths
  # resources :articles

end
